# Generated by Django 2.2.4 on 2019-09-13 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsinfo',
            name='gadv',
        ),
    ]
